# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weatherApi.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 559)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/imgs/images/Jk5bLa.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_whereLocation = QtWidgets.QLabel(self.centralwidget)
        self.label_whereLocation.setGeometry(QtCore.QRect(20, 50, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_whereLocation.setFont(font)
        self.label_whereLocation.setStyleSheet("background-color: rgb(175, 206, 255);")
        self.label_whereLocation.setIndent(-5)
        self.label_whereLocation.setObjectName("label_whereLocation")
        self.label_humidity = QtWidgets.QLabel(self.centralwidget)
        self.label_humidity.setGeometry(QtCore.QRect(20, 220, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_humidity.setFont(font)
        self.label_humidity.setStyleSheet("background-color: rgb(175, 206, 255);")
        self.label_humidity.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_humidity.setObjectName("label_humidity")
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setGeometry(QtCore.QRect(450, 90, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp.setFont(font)
        self.label_temp.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_temp.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_temp.setWordWrap(False)
        self.label_temp.setObjectName("label_temp")
        self.label_pressure = QtWidgets.QLabel(self.centralwidget)
        self.label_pressure.setGeometry(QtCore.QRect(20, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_pressure.setFont(font)
        self.label_pressure.setStyleSheet("background-color: rgb(175, 206, 255);")
        self.label_pressure.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_pressure.setObjectName("label_pressure")
        self.label_temp_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_2.setGeometry(QtCore.QRect(520, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_2.setFont(font)
        self.label_temp_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_temp_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_temp_2.setWordWrap(False)
        self.label_temp_2.setObjectName("label_temp_2")
        self.label_temp_feeling_like = QtWidgets.QLabel(self.centralwidget)
        self.label_temp_feeling_like.setGeometry(QtCore.QRect(330, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_temp_feeling_like.setFont(font)
        self.label_temp_feeling_like.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_temp_feeling_like.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_temp_feeling_like.setWordWrap(False)
        self.label_temp_feeling_like.setObjectName("label_temp_feeling_like")
        self.lineEdit_NameorID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_NameorID.setGeometry(QtCore.QRect(320, 10, 191, 20))
        self.lineEdit_NameorID.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.lineEdit_NameorID.setObjectName("lineEdit_NameorID")
        self.pushButton_Search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Search.setGeometry(QtCore.QRect(530, 10, 75, 23))
        self.pushButton_Search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Search.setAutoFillBackground(False)
        self.pushButton_Search.setAutoRepeat(False)
        self.pushButton_Search.setObjectName("pushButton_Search")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather API"))
        self.label_whereLocation.setText(_translate("MainWindow", "place"))
        self.label_humidity.setText(_translate("MainWindow", "humidity"))
        self.label_temp.setText(_translate("MainWindow", "temp"))
        self.label_pressure.setText(_translate("MainWindow", "pressure"))
        self.label_temp_2.setText(_translate("MainWindow", "temp_min/ temp_max"))
        self.label_temp_feeling_like.setText(_translate("MainWindow", "Temp Feels like 22 C"))
        self.lineEdit_NameorID.setText(_translate("MainWindow", "Nairobi"))
        self.lineEdit_NameorID.setPlaceholderText(_translate("MainWindow", "Enter City\'s Name or ISO ID"))
        self.pushButton_Search.setText(_translate("MainWindow", "Search"))
import weather_img_rc
